mongodb_uri = ""
rabbitmq_uri = ""
manager_url = ""
manager_port = ""
signing_timeout = ""
threshold = ""
total_parties = ""
path = ""
signer1_key_file = ""
signer2_key_file = ""
signer3_key_file = ""
